

y_Reslice('./output_3.nii.gz', './tvalue_aligned_left_finger_motor.nii.gz', ...
    [1 1 1], 1, ...
    '../T1w_acpc_dc_restore_brain.nii.gz');
y_Reslice('./output_6.nii.gz', './tvalue_aligned_right_finger_motor.nii.gz', ...
    [1 1 1], 1, ...
    '../T1w_acpc_dc_restore_brain.nii.gz');
